// Search-only portfolio metadata. These tags stay out of the visible project
// pages, but give the archive a consistent vocabulary for tools, materials,
// skills, media, platforms, roles, and themes.
export const PORTFOLIO_RECORDS = [
  {
    id: "digital-sociology-study",
    href: "/digital-sociology-study",
    title: "Digital Sociology Study",
    category: "Study",
    year: 2025,
    programs: ["Unity", "Maya", "Blender", "Substance Painter", "Cursor"],
    materials: ["Meta Quest 3", "buttons", "composite board", "Adafruit Bitsy", "electronics"],
    skills: ["VR development", "game development", "3D modeling", "3D texturing", "experience design", "interaction design", "physical computing", "networked systems", "world building", "installation design"],
    mediums: ["VR installation", "interactive installation", "networked experience", "mixed-media installation"],
    platforms: ["Meta Quest 3"],
    participants: ["2 players", "up to 5 observers"],
    duration: ["approximately 5 minutes minimum", "5-minute minimum"],
    themes: ["digital sociology", "social behavior", "anonymity", "digital identity", "embodiment", "audience participation"],
    aliases: ["VR", "virtual reality", "XR", "immersive", "Quest", "multiplayer", "participatory art", "interactive art"],
  },
  {
    id: "small-planetarium",
    href: "/digital/planetarium",
    title: "Small Planetarium",
    category: "Digital",
    year: 2026,
    programs: ["SketchUp", "Blender"],
    skills: ["3D modeling", "environment design", "spatial design", "exhibition design", "architectural visualization"],
    mediums: ["3D environment", "digital model", "exhibition concept"],
    themes: ["planetarium", "astronomy", "museum", "gems and minerals"],
    aliases: ["3D", "immersive environment", "museum design"],
  },
  {
    id: "merimnao",
    href: "/digital/merimnao",
    title: "Merimnao",
    category: "Digital",
    year: 2024,
    programs: ["Unity"],
    skills: ["game development", "game design", "level design", "world building", "interaction design"],
    mediums: ["video game", "horror game", "maze game"],
    platforms: ["Windows", "PC"],
    themes: ["dread", "anticipatory anxiety", "surrealism", "reverse hide and seek"],
    aliases: ["interactive", "real-time 3D", "PC game"],
  },
  {
    id: "simulation",
    href: "/digital/simulation",
    title: "Simulation",
    category: "Digital",
    year: 2023,
    programs: ["Unity", "Meta OpenXR"],
    materials: ["Meta Quest 2"],
    skills: ["mixed reality development", "VR development", "game development", "gameplay design", "interaction design", "experience design"],
    mediums: ["mixed reality game", "VR game", "immersive experience"],
    platforms: ["Meta Quest 2", "OpenXR"],
    themes: ["simulation", "passthrough", "perception", "play"],
    aliases: ["VR", "virtual reality", "MR", "XR", "Quest", "immersive game"],
  },
  {
    id: "shasta",
    href: "/digital/shasta-animated-short",
    title: "Shasta",
    category: "Digital",
    year: 2022,
    programs: ["Adobe After Effects"],
    skills: ["animation", "motion design", "motion graphics", "video editing", "visual storytelling"],
    mediums: ["animated short", "short film", "video"],
    themes: ["Shasta Groene", "true story", "narrative"],
    aliases: ["After Effects", "AE", "animation"],
  },
  {
    id: "medieval-bestiary-entries",
    href: "/digital/collection",
    title: "Medieval Bestiary Entries.org",
    category: "Digital",
    year: 2023,
    programs: ["HTML", "p5.js", "Stable Diffusion"],
    skills: ["creative coding", "web development", "generative AI", "AI image generation", "art direction"],
    mediums: ["interactive website", "web art", "AI-generated imagery"],
    platforms: ["Web"],
    themes: ["misinformation", "fake news", "synthetic media", "medieval bestiary", "truth"],
    aliases: ["AI", "artificial intelligence", "JavaScript", "p5js", "generative art"],
  },
  {
    id: "siphonophora",
    href: "/digital/collection",
    title: "Siphonophora",
    category: "Digital",
    year: 2023,
    programs: ["HTML", "p5.js"],
    skills: ["creative coding", "web development", "interaction design", "procedural animation", "simulation design"],
    mediums: ["immersive web experience", "interactive simulation", "web art"],
    platforms: ["Web"],
    themes: ["siphonophores", "colonial organisms", "ecology", "collaboration", "growth", "cloning"],
    aliases: ["JavaScript", "p5js", "interactive art", "digital biology"],
  },
  {
    id: "vanitas",
    href: "/digital/collection",
    title: "Vanitas",
    category: "Digital",
    year: 2023,
    programs: ["Pika"],
    materials: ["silicone", "wood"],
    skills: ["generative AI", "AI animation", "installation design", "fabrication", "art direction"],
    mediums: ["AI installation", "mixed-media installation", "moving image"],
    themes: ["vanitas", "luxury", "desire", "mortality", "classical painting"],
    aliases: ["AI", "artificial intelligence", "generative art", "video installation"],
  },
  {
    id: "decoding-disease",
    href: "/digital/collection",
    title: "Decoding Disease",
    category: "Digital",
    year: 2023,
    programs: ["Runway ML"],
    skills: ["VR experience design", "generative AI", "prompt design", "immersive storytelling", "installation design"],
    mediums: ["VR art installation", "virtual gallery", "AI-generated imagery"],
    themes: ["disease", "human health", "artificial intelligence", "machine perception"],
    aliases: ["VR", "virtual reality", "XR", "immersive", "AI", "machine learning"],
  },
  {
    id: "i-think-therefore-i-am-human",
    href: "/digital/collection",
    title: "I_Think_Therefore_I_Am_Human",
    category: "Digital",
    year: 2022,
    programs: ["Processing", "This Person Does Not Exist"],
    skills: ["creative coding", "generative AI", "image curation", "visual research"],
    mediums: ["generative image series", "digital art"],
    themes: ["identity", "humanity", "synthetic people", "uncanny images"],
    aliases: ["AI", "artificial intelligence", "GAN", "generated faces"],
  },
  {
    id: "games-glitches-creativity",
    href: "/digital/collection",
    title: "Games, Glitches and Creativity",
    category: "Digital",
    year: 2023,
    programs: ["HTML", "CSS", "Twine"],
    skills: ["web development", "creative coding", "interactive narrative", "game design"],
    mediums: ["web game", "interactive fiction", "browser-based artwork"],
    platforms: ["Web"],
    themes: ["games", "glitches", "creativity", "nonlinear storytelling"],
    aliases: ["interactive story", "hypertext", "web art"],
  },
  {
    id: "digital-planetarium",
    href: "/digital/digital-planetarium",
    title: "Digital Planetarium",
    category: "Digital",
    year: 2022,
    programs: ["p5.js", "HTML", "WebGL", "Runway AI"],
    skills: ["creative coding", "web development", "interaction design", "AI frame interpolation", "data sonification", "audio generation"],
    mediums: ["interactive web experience", "digital planetarium", "data-driven artwork"],
    platforms: ["Web"],
    themes: ["astronomy", "space", "Hubble telescope", "James Webb telescope", "image data"],
    aliases: ["AI", "artificial intelligence", "JavaScript", "p5js", "generative art", "NASA"],
  },
  {
    id: "biotic-gallery",
    href: "/digital/biotic-gallery",
    title: "Biotic Gallery",
    category: "Digital",
    year: 2024,
    programs: ["Unreal Engine 5", "Maya", "Substance Painter"],
    skills: ["3D modeling", "polygon modeling", "3D texturing", "shading", "environment design", "real-time rendering"],
    mediums: ["real-time 3D gallery", "digital environment"],
    platforms: ["Unreal Engine"],
    themes: ["organics", "biotic forms", "gallery", "digital nature"],
    aliases: ["3D", "UE5", "game engine", "immersive environment"],
  },
  {
    id: "witches-flight-3d",
    href: "/digital/witches-flight-3d",
    title: "Witches' Flight 3D",
    category: "Digital",
    year: 2024,
    programs: ["Maya", "ZBrush", "Substance Painter"],
    skills: ["3D modeling", "digital sculpting", "3D texturing", "asset creation", "art-historical recreation"],
    mediums: ["3D artwork", "digital sculpture", "image"],
    themes: ["Francisco Goya", "Witches' Flight", "painting recreation", "art history"],
    aliases: ["3D", "Z-brush", "CGI", "digital modeling"],
  },
  {
    id: "identity-automaton",
    href: "/digital/identity-automaton",
    title: "Identity Automaton",
    category: "Digital",
    year: 2022,
    programs: ["Cables.gl", "MediaPipe"],
    skills: ["creative coding", "computer vision", "motion tracking", "rigging", "web development", "interaction design"],
    mediums: ["interactive web artwork", "motion-tracked experience", "digital installation"],
    platforms: ["Web"],
    themes: ["online identity", "social media", "embodiment", "Instagram", "human-computer relationship"],
    aliases: ["AI", "camera tracking", "body tracking", "interactive art"],
  },
  {
    id: "deficit",
    href: "/digital/deficit",
    title: "Deficit",
    category: "Digital",
    year: 2022,
    programs: ["Unreal Engine 5"],
    materials: ["Meta Quest"],
    skills: ["VR development", "experience design", "immersive storytelling", "real-time 3D"],
    mediums: ["VR experience", "immersive simulation"],
    platforms: ["Meta Quest"],
    themes: ["attention deficit disorder", "ADHD", "neurodiversity", "attention"],
    aliases: ["VR", "virtual reality", "XR", "Quest", "immersive"],
  },
  {
    id: "stories-on-skin",
    href: "/physical/storiesonskin",
    title: "Stories on Skin",
    category: "Physical",
    year: 2023,
    materials: ["silicone", "electronics", "audio", "wood", "pigment", "buttons", "speakers"],
    skills: ["life casting", "mold making", "casting", "physical computing", "electronics", "sound design", "fabrication", "interaction design"],
    mediums: ["interactive installation", "sculpture", "sound art", "touch-based artwork"],
    themes: ["scars", "body", "memory", "oral history", "touch", "personal stories"],
    aliases: ["interactive art", "participatory art", "tactile installation"],
  },
  {
    id: "decay",
    href: "/physical/decay",
    title: "Decay",
    category: "Physical",
    year: 2023,
    materials: ["wood", "PLA", "magnets", "DC motor"],
    skills: ["3D printing", "model making", "physical computing", "kinetic fabrication", "motor control", "interaction design"],
    mediums: ["kinetic sculpture", "interactive installation", "physical computing"],
    themes: ["decay", "preservation", "impermanence", "Castle Williams", "Governors Island"],
    aliases: ["interactive art", "motorized sculpture", "Flux Factory", "Nothing Island"],
  },
  {
    id: "industrial-woman",
    href: "/physical/the-industrial-woman",
    title: "The Industrial Woman",
    category: "Physical",
    year: 2023,
    programs: ["Arduino"],
    materials: ["DC motor", "Arduino", "plastic", "wood", "metal"],
    skills: ["physical computing", "electronics", "robotics", "kinetic fabrication", "motor control", "prototyping"],
    mediums: ["kinetic sculpture", "interactive installation"],
    themes: ["domestic labor", "capitalism", "feminism", "housework", "exploitation"],
    aliases: ["interactive art", "motorized sculpture", "mechatronics"],
  },
  {
    id: "coyness",
    href: "/physical/coyness",
    title: "Coyness",
    category: "Physical",
    year: 2024,
    programs: ["Arduino"],
    materials: ["servos", "Arduino", "fabric", "PLA", "wire"],
    skills: ["physical computing", "electronics", "robotics", "wearable technology", "hardware design", "interaction design", "proximity sensing"],
    mediums: ["interactive garment", "kinetic dress", "wearable sculpture"],
    themes: ["flirtation", "historical dress", "animal behavior", "fashion", "biomimicry"],
    roles: ["robotics", "hardware"],
    aliases: ["wearable tech", "fashion technology", "interactive fashion", "mechatronics"],
  },
  {
    id: "cinderella-costume-production",
    href: "/physical/theater-production-work",
    title: "Fiorello LaGuardia High School's Cinderella",
    category: "Physical",
    year: 2020,
    skills: ["sewing", "costume construction", "menswear", "garment construction", "theater production"],
    mediums: ["costume production", "musical theater"],
    roles: ["head of men's dress", "seamstress"],
    themes: ["Cinderella", "Rodgers and Hammerstein", "performance"],
    aliases: ["costume design", "wardrobe", "theatrical costume"],
  },
  {
    id: "smtw-the-witches",
    href: "/physical/theater-production-work",
    title: "SMTW: The Witches",
    category: "Physical",
    year: 2019,
    skills: ["theater production", "low-budget fabrication", "production design", "collaboration"],
    mediums: ["musical theater", "stage production"],
    themes: ["The Witches", "performance", "Kaufman Music Center"],
    aliases: ["theatrical production", "Summer Musical Theater Workshop", "SMTW"],
  },
  {
    id: "august-osage-county",
    href: "/physical/theater-production-work",
    title: "August: Osage County",
    category: "Physical",
    year: 2018,
    skills: ["theater production", "scenic construction", "fabrication", "stagecraft"],
    mediums: ["drama production", "stage production"],
    roles: ["build crew"],
    themes: ["August: Osage County", "performance", "theater"],
    aliases: ["theatrical production", "set construction", "crew"],
  },
  {
    id: "african-bullfrog",
    href: "/physical/african-bullfrog",
    title: "African Bullfrog",
    category: "Physical",
    year: 2026,
    programs: ["Polycam"],
    materials: ["clay", "silicone", "fiberglass", "foam", "resin", "paint"],
    skills: ["hand sculpting", "mold making", "casting", "fiberglass fabrication", "airbrushing", "hand painting", "3D scanning", "3D printing", "digital fabrication"],
    mediums: ["sculpture", "animal model", "digital scan", "resin print"],
    themes: ["natural history", "museum model", "African bullfrog", "digital and traditional craft"],
    aliases: ["3D", "photogrammetry", "8K resin", "model making"],
  },
  {
    id: "milken-center-ellwas",
    href: "/for-clients/mcadxellwas",
    title: "Milken Center for Advancing the American Dream x Ellwas",
    category: "Client",
    year: 2022,
    skills: ["experience design", "interaction design", "museum design", "concept development", "UI design", "visitor journey design"],
    mediums: ["museum experience", "interactive exhibit concept", "mobile UI"],
    roles: ["design intern"],
    themes: ["American Dream", "personalization", "visitor journey", "responsive light"],
    aliases: ["UX", "user experience", "exhibition design", "experiential design"],
  },
  {
    id: "wikipedia-galaxy",
    href: "/for-clients/aippy",
    title: "Wikipedia Galaxy",
    category: "Client",
    year: 2025,
    programs: ["Aippy", "Wikipedia"],
    skills: ["creative coding", "data visualization", "network visualization", "information design", "generative systems"],
    mediums: ["interactive data visualization", "web artwork", "network map"],
    platforms: ["Web", "Aippy"],
    themes: ["Wikipedia", "knowledge networks", "constellations", "traffic data", "linked information"],
    aliases: ["AI", "algorithmic art", "graph visualization", "data art"],
  },
  {
    id: "fourth-eye",
    href: "/for-clients/aippy",
    title: "Fourth Eye",
    category: "Client",
    year: 2025,
    programs: ["Aippy", "MediaPipe"],
    skills: ["creative coding", "computer vision", "eye tracking", "camera interaction", "interaction design"],
    mediums: ["interactive camera artwork", "computer vision experience", "web artwork"],
    platforms: ["Web", "Aippy"],
    themes: ["blinking", "eye movement", "gaze", "intimacy", "responsive animation"],
    aliases: ["AI", "face tracking", "vision tracking", "interactive art"],
  },
  {
    id: "black-luminaries",
    href: "/for-clients/black-luminaries",
    title: "Black Luminaries",
    category: "Client",
    year: 2026,
    skills: ["client collaboration", "interactive experience production"],
    mediums: ["interactive game", "event experience"],
    themes: ["Black history", "Juneteenth", "innovation", "African American community"],
    aliases: ["Black Heart", "African American Chamber of Commerce of New Jersey", "Juneteenth Innovation Expo"],
  },
];

// Query expansions make common shorthand useful without adding every possible
// spelling to every project record. Direct tag matches still rank highest.
export const SEARCH_ALIASES = {
  vr: ["virtual reality", "mixed reality", "xr", "meta quest"],
  "virtual reality": ["vr", "xr", "meta quest"],
  mr: ["mixed reality", "xr", "passthrough"],
  xr: ["vr", "virtual reality", "mixed reality", "meta quest"],
  ai: ["artificial intelligence", "generative ai", "machine learning"],
  "3d": ["3d modeling", "digital sculpting", "3d scanning", "3d printing", "real-time 3d"],
  ux: ["user experience", "experience design", "interaction design"],
  ui: ["user interface", "ui design"],
  code: ["creative coding", "web development", "game development"],
  sculpture: ["sculpture", "model making", "casting", "kinetic sculpture"],
};
